#!/bin/sh

printf "🔧 running pre-commit hooks ...\n"
if [ -n "$(make check)" ]; then
    echo >&2 "--------------------------------"
    echo >&2 "🚨 [error] some files are changed, please add them to the staging area and commit again"
    echo >&2 "--------------------------------"
    exit 1
fi

echo "✅ [success] pre-commit hooks passed"
exit 0
